import Card from "#models/card";
import Minion from "#models/minion";
import { BaseSeeder } from "@adonisjs/lucid/seeders";

export default class extends BaseSeeder {
    async run() {
        const [
            monsterOneOne,
            monsterTwoOne,
            monsterOneTwo,
            monsterTwoTwo,
            monsterThreeOne,
            monsterThreeThree,
            monsterFiveTwo,
            monsterFiveFour,
            monsterSixSix,
            monsterSixEight,
            monsterEightSix,
            monsterSevenSeven,
            monsterSevenNine,
            monsterNineSeven,
            monsterEightEight,
            monsterEightTen,
            monsterTenEight,
            monsterNineNine,
        ] = await Minion.createMany([
            {
                internalLabel: "Monstre 1-1",
                attack: 1,
                health: 1,
            },
            {
                internalLabel: "Monstre 2-1",
                attack: 2,
                health: 1,
            },
            {
                internalLabel: "Monstre 1-2",
                attack: 1,
                health: 2,
            },
            {
                internalLabel: "Monstre 2-2",
                attack: 2,
                health: 2,
            },
            {
                internalLabel: "Monstre 3-1",
                attack: 3,
                health: 1,
            },
            {
                internalLabel: "Monstre 3-3",
                attack: 3,
                health: 3,
            },
            {
                internalLabel: "Monstre 5-2",
                attack: 5,
                health: 2,
            },
            {
                internalLabel: "Monstre 5-4",
                attack: 5,
                health: 4,
            },
            {
                internalLabel: "Monstre 6-6",
                attack: 6,
                health: 6,
            },
            {
                internalLabel: "Monstre 6-8",
                attack: 6,
                health: 8,
            },
            {
                internalLabel: "Monstre 8-6",
                attack: 8,
                health: 6,
            },
            {
                internalLabel: "Monstre 7-7",
                attack: 7,
                health: 7,
            },
            {
                internalLabel: "Monstre 7-9",
                attack: 7,
                health: 9,
            },
            {
                internalLabel: "Monstre 9-7",
                attack: 9,
                health: 7,
            },
            {
                internalLabel: "Monstre 8-8",
                attack: 8,
                health: 8,
            },
            {
                internalLabel: "Monstre 8-10",
                attack: 8,
                health: 10,
            },
            {
                internalLabel: "Monstre 10-8",
                attack: 10,
                health: 8,
            },
            {
                internalLabel: "Monstre 9-9",
                attack: 9,
                health: 9,
            },
        ]);

        await Card.createMany([
            {
                label: "Monster 1-1",
                imageUrl: "https://picsum.photos/seed/monster_1-1/200/300",
                cost: 1,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterOneOne.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 2-1",
                imageUrl: "https://picsum.photos/seed/monster_2-1/200/300",
                cost: 2,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterTwoOne.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 1-2",
                imageUrl: "https://picsum.photos/seed/monster_1-2/200/300",
                cost: 2,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterOneTwo.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 2-2",
                imageUrl: "https://picsum.photos/seed/monster_2-2/200/300",
                cost: 3,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterTwoTwo.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 3-1",
                imageUrl: "https://picsum.photos/seed/monster_3-1/200/300",
                cost: 3,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterThreeOne.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 3-3",
                imageUrl: "https://picsum.photos/seed/monster_3-3/200/300",
                cost: 4,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterThreeThree.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 5-2",
                imageUrl: "https://picsum.photos/seed/monster_5-2/200/300",
                cost: 5,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterFiveTwo.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 5-4",
                imageUrl: "https://picsum.photos/seed/monster_5-4/200/300",
                cost: 6,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterFiveFour.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 6-6",
                imageUrl: "https://picsum.photos/seed/monster_6-6/200/300",
                cost: 7,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterSixSix.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 6-8",
                imageUrl: "https://picsum.photos/seed/monster_6-8/200/300",
                cost: 8,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterSixEight.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 8-6",
                imageUrl: "https://picsum.photos/seed/monster_8-6/200/300",
                cost: 9,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterEightSix.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 7-7",
                imageUrl: "https://picsum.photos/seed/monster_7-7/200/300",
                cost: 8,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterSevenSeven.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 7-9",
                imageUrl: "https://picsum.photos/seed/monster_7-9/200/300",
                cost: 9,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterSevenNine.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 9-7",
                imageUrl: "https://picsum.photos/seed/monster_9-7/200/300",
                cost: 9,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterNineSeven.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 8-8",
                imageUrl: "https://picsum.photos/seed/monster_8-8/200/300",
                cost: 9,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterEightEight.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 8-10",
                imageUrl: "https://picsum.photos/seed/monster_8-10/200/300",
                cost: 10,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterEightTen.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 10-8",
                imageUrl: "https://picsum.photos/seed/monster_10-8/200/300",
                cost: 10,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterTenEight.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Monster 9-9",
                imageUrl: "https://picsum.photos/seed/monster_9-9/200/300",
                cost: 10,
                type: "MINION",
                cardMode: "BETA",
                minionId: monsterNineNine.id,
                spellId: null,
                weaponId: null,
            },
        ]);
    }
}
