import Card from "#models/card";
import CardTag from "#models/card_tag";
import Minion from "#models/minion";
import MinionPower from "#models/minion_power";
import Tag from "#models/tag";
import { BaseSeeder } from "@adonisjs/lucid/seeders";
import { getClassicCardImage } from "../seed_data/classic_card_images.js";

export default class extends BaseSeeder {
    async run() {
        const tauntPower = await MinionPower.create({
            hasTaunt: true,
            hasCharge: false,
            hasWindfury: false,
            isPoisonous: false,
        });

        const chargePower = await MinionPower.create({
            hasTaunt: false,
            hasCharge: true,
            hasWindfury: false,
            isPoisonous: false,
        });

        const windfuryPower = await MinionPower.create({
            hasTaunt: false,
            hasCharge: false,
            hasWindfury: true,
            isPoisonous: false,
        });

        const poisonousPower = await MinionPower.create({
            hasTaunt: false,
            hasCharge: false,
            hasWindfury: false,
            isPoisonous: true,
        });

        const [beastTag, mechTag] = await Tag.createMany([
            { name: "beast", symbol: "🦁", label: "Bête" },
            { name: "mech", symbol: "⚙️", label: "Méca" },
        ]);

        const [
            lutin,
            eclaireurPandaren,
            sanglier,
            porteBouclier,
            jeuneFauconDragon,
            dragonMecanique,
            moineShadoPan,
            cobraEmpereur,
            patriarcheDosArgente,
            guerrierTauren,
            farseerThrallmar,
            maitreBrasseur,
            chevalierHurlevent,
            corsaireRedoutable,
            dimetrodon,
            leeroyJenkins,
            rampantFondrieres,
            commandantArgente,
            harpieFurieDesVents,
            seigneurArene,
            geantDesMers,
        ] = await Minion.createMany([
            { internalLabel: "Lutin", attack: 1, health: 1 },
            { internalLabel: "Éclaireur pandaren", attack: 1, health: 1 },
            { internalLabel: "Sanglier", attack: 1, health: 1 },
            {
                internalLabel: "Porte-bouclier",
                attack: 0,
                health: 4,
                minionPowerId: tauntPower.id,
            },
            {
                internalLabel: "Jeune faucon-dragon",
                attack: 1,
                health: 1,
                minionPowerId: windfuryPower.id,
            },
            { internalLabel: "Dragon mécanique", attack: 2, health: 1 },
            { internalLabel: "Moine du Shado-Pan", attack: 2, health: 2 },
            {
                internalLabel: "Cobra empereur",
                attack: 2,
                health: 3,
                minionPowerId: poisonousPower.id,
            },
            {
                internalLabel: "Patriarche dos-argenté",
                attack: 1,
                health: 4,
                minionPowerId: tauntPower.id,
            },
            {
                internalLabel: "Guerrier tauren",
                attack: 2,
                health: 3,
                minionPowerId: tauntPower.id,
            },
            {
                internalLabel: "Farseer de Thrallmar",
                attack: 2,
                health: 3,
                minionPowerId: windfuryPower.id,
            },
            { internalLabel: "Maître brasseur", attack: 4, health: 4 },
            {
                internalLabel: "Chevalier de Hurlevent",
                attack: 2,
                health: 5,
                minionPowerId: chargePower.id,
            },
            {
                internalLabel: "Corsaire redoutable",
                attack: 3,
                health: 3,
                minionPowerId: tauntPower.id,
            },
            { internalLabel: "Dimetrodon", attack: 5, health: 5 },
            {
                internalLabel: "Leeroy Jenkins",
                attack: 6,
                health: 2,
                minionPowerId: chargePower.id,
            },
            {
                internalLabel: "Rampant des fondrières",
                attack: 3,
                health: 6,
                minionPowerId: tauntPower.id,
            },
            {
                internalLabel: "Commandant argenté",
                attack: 4,
                health: 2,
                minionPowerId: chargePower.id,
            },
            {
                internalLabel: "Harpie furie des vents",
                attack: 4,
                health: 5,
                minionPowerId: windfuryPower.id,
            },
            {
                internalLabel: "Seigneur de l'Arène",
                attack: 6,
                health: 5,
                minionPowerId: tauntPower.id,
            },
            { internalLabel: "Géant des mers", attack: 8, health: 8 },
        ]);

        const cards = await Card.createMany([
            {
                label: "Lutin",
                imageUrl: getClassicCardImage("lutin"),
                cost: 0,
                type: "MINION",
                cardMode: "BETA",
                minionId: lutin.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Éclaireur pandaren",
                imageUrl: getClassicCardImage("eclaireur_pandaren"),
                cost: 1,
                type: "MINION",
                cardMode: "BETA",
                minionId: eclaireurPandaren.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Sanglier",
                imageUrl: getClassicCardImage("sanglier"),
                cost: 1,
                type: "MINION",
                cardMode: "BETA",
                minionId: sanglier.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Porte-bouclier",
                imageUrl: getClassicCardImage("porte_bouclier"),
                cost: 1,
                type: "MINION",
                cardMode: "BETA",
                minionId: porteBouclier.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Jeune faucon-dragon",
                imageUrl: getClassicCardImage("jeune_faucon_dragon"),
                cost: 1,
                type: "MINION",
                cardMode: "BETA",
                minionId: jeuneFauconDragon.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Dragon mécanique",
                imageUrl: getClassicCardImage("dragon_mecanique"),
                cost: 1,
                type: "MINION",
                cardMode: "BETA",
                minionId: dragonMecanique.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Moine du Shado-Pan",
                imageUrl: getClassicCardImage("moine_shado_pan"),
                cost: 2,
                type: "MINION",
                cardMode: "BETA",
                minionId: moineShadoPan.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Cobra empereur",
                imageUrl: getClassicCardImage("cobra_empereur"),
                cost: 3,
                type: "MINION",
                cardMode: "BETA",
                minionId: cobraEmpereur.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Patriarche dos-argenté",
                imageUrl: getClassicCardImage("patriarche_dos_argente"),
                cost: 3,
                type: "MINION",
                cardMode: "BETA",
                minionId: patriarcheDosArgente.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Guerrier tauren",
                imageUrl: getClassicCardImage("guerrier_tauren"),
                cost: 3,
                type: "MINION",
                cardMode: "BETA",
                minionId: guerrierTauren.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Farseer de Thrallmar",
                imageUrl: getClassicCardImage("farseer_thrallmar"),
                cost: 3,
                type: "MINION",
                cardMode: "BETA",
                minionId: farseerThrallmar.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Maître brasseur",
                imageUrl: getClassicCardImage("maitre_brasseur"),
                cost: 4,
                type: "MINION",
                cardMode: "BETA",
                minionId: maitreBrasseur.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Chevalier de Hurlevent",
                imageUrl: getClassicCardImage("chevalier_hurlevent"),
                cost: 4,
                type: "MINION",
                cardMode: "BETA",
                minionId: chevalierHurlevent.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Corsaire redoutable",
                imageUrl: getClassicCardImage("corsaire_redoutable"),
                cost: 4,
                type: "MINION",
                cardMode: "BETA",
                minionId: corsaireRedoutable.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Dimetrodon",
                imageUrl: getClassicCardImage("dimetrodon"),
                cost: 5,
                type: "MINION",
                cardMode: "BETA",
                minionId: dimetrodon.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Leeroy Jenkins",
                imageUrl: getClassicCardImage("leeroy_jenkins"),
                cost: 5,
                type: "MINION",
                cardMode: "BETA",
                minionId: leeroyJenkins.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Rampant des fondrières",
                imageUrl: getClassicCardImage("rampant_fondrieres"),
                cost: 5,
                type: "MINION",
                cardMode: "BETA",
                minionId: rampantFondrieres.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Commandant argenté",
                imageUrl: getClassicCardImage("commandant_argente"),
                cost: 6,
                type: "MINION",
                cardMode: "BETA",
                minionId: commandantArgente.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Harpie furie des vents",
                imageUrl: getClassicCardImage("harpie_furie_des_vents"),
                cost: 6,
                type: "MINION",
                cardMode: "BETA",
                minionId: harpieFurieDesVents.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Seigneur de l'Arène",
                imageUrl: getClassicCardImage("seigneur_arene"),
                cost: 6,
                type: "MINION",
                cardMode: "BETA",
                minionId: seigneurArene.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Géant des mers",
                imageUrl: getClassicCardImage("geant_des_mers"),
                cost: 10,
                type: "MINION",
                cardMode: "BETA",
                minionId: geantDesMers.id,
                spellId: null,
                weaponId: null,
            },
        ]);

        const cardByMinionId = new Map(cards.map((c) => [c.minionId, c]));

        await CardTag.createMany([
            { cardId: cardByMinionId.get(sanglier.id)!.id, tagId: beastTag.id },
            { cardId: cardByMinionId.get(jeuneFauconDragon.id)!.id, tagId: beastTag.id },
            { cardId: cardByMinionId.get(patriarcheDosArgente.id)!.id, tagId: beastTag.id },
            { cardId: cardByMinionId.get(dimetrodon.id)!.id, tagId: beastTag.id },
            { cardId: cardByMinionId.get(dragonMecanique.id)!.id, tagId: mechTag.id },
        ]);
    }
}
