import Action from "#models/action";
import Boost from "#models/boost";
import Card from "#models/card";
import CardFilter from "#models/card_filter";
import CardSet from "#models/card_set";
import CardTag from "#models/card_tag";
import Comparison from "#models/comparison";
import Minion from "#models/minion";
import MinionBattlecryAction from "#models/minion_battlecry_action";
import MinionDeathrattleAction from "#models/minion_deathrattle_action";
import MinionPassive from "#models/minon_passive";
import MinionPower from "#models/minion_power";
import Passive from "#models/passive";
import Spell from "#models/spell";
import Tag from "#models/tag";
import Target from "#models/target";
import ToolToTarget from "#models/tool_to_target";
import Weapon from "#models/weapon";
import WeaponDeathrattleAction from "#models/weapon_deathrattle_action";
import { BaseSeeder } from "@adonisjs/lucid/seeders";
import { GALADRIM_CARD_SET_NAME } from "../seed_data/card_set_names.js";
import { getGaladrimCardImage } from "../seed_data/galadrim_card_images.js";

const nullActionFields = {
    drawCount: null,
    drawCardFilterId: null,
    enemyDrawCount: null,
    enemyDrawCardFilterId: null,
    damage: null,
    heal: null,
    boostId: null,
};

export default class extends BaseSeeder {
    async run() {
        const galadrimSet = await CardSet.findByOrFail("name", GALADRIM_CARD_SET_NAME);

        const [tauntPower, chargePower, windfuryPower, poisonousPower] = await Promise.all([
            MinionPower.query().where("hasTaunt", true).firstOrFail(),
            MinionPower.query().where("hasCharge", true).firstOrFail(),
            MinionPower.query().where("hasWindfury", true).firstOrFail(),
            MinionPower.query().where("isPoisonous", true).firstOrFail(),
        ]);

        const [developpeurTag, pmTag, parisienTag, nantaisTag, lyonnaisTag, petsTag] =
            await Tag.createMany([
                { name: "developpeur", symbol: "💻", label: "Développeur" },
                { name: "pm", symbol: "📊", label: "PM" },
                { name: "parisien", symbol: "📍", label: "Parisien" },
                { name: "nantais", symbol: "📍", label: "Nantais" },
                { name: "lyonnais", symbol: "📍", label: "Lyonnais" },
                { name: "pets", symbol: "🐾", label: "Pets" },
            ]);

        const costAtMostThreeComparison = await Comparison.create({
            costComparison: "<",
            cost: 4,
            attackComparison: null,
            attack: null,
            healthComparison: null,
            health: null,
        });

        const [spellDrawFilter, minionDrawFilter, developpeurDrawFilter, cheapMinionDrawFilter] =
            await CardFilter.createMany([
                { internalLabel: "Galadrim - Pioche un sort", type: "SPELL", comparisonId: null },
                {
                    internalLabel: "Galadrim - Pioche un serviteur",
                    type: "MINION",
                    comparisonId: null,
                },
                {
                    internalLabel: "Galadrim - Pioche un développeur",
                    type: "MINION",
                    comparisonId: null,
                },
                {
                    internalLabel: "Galadrim - Pioche un serviteur coût ≤ 3",
                    type: "MINION",
                    comparisonId: costAtMostThreeComparison.id,
                },
            ]);

        await developpeurDrawFilter.related("tags").attach([developpeurTag.id]);

        const [
            allyHeroTarget,
            enemyHeroTarget,
            enemyMinionsTarget,
            allyMinionsTarget,
            allMinionsTarget,
            randomEnemyTarget,
            targetedAllyMinionTarget,
            targetedAnyMinionTarget,
            otherDeveloppeursTarget,
            otherPetsTarget,
            otherAllyMinionsTarget,
        ] = await Target.createMany([
            {
                internalLabel: "Galadrim - Héros allié",
                type: "HERO",
                targetTeam: "PLAYER",
                comparisonId: null,
                tagId: null,
            },
            {
                internalLabel: "Galadrim - Héros adverse",
                type: "HERO",
                targetTeam: "OPPONENT",
                comparisonId: null,
                tagId: null,
            },
            {
                internalLabel: "Galadrim - Serviteurs adverses",
                type: "MINION",
                targetTeam: "OPPONENT",
                comparisonId: null,
                tagId: null,
            },
            {
                internalLabel: "Galadrim - Serviteurs alliés",
                type: "MINION",
                targetTeam: "PLAYER",
                comparisonId: null,
                tagId: null,
            },
            {
                internalLabel: "Galadrim - Tous les serviteurs",
                type: "MINION",
                targetTeam: "ALL",
                comparisonId: null,
                tagId: null,
            },
            {
                internalLabel: "Galadrim - Cibles ennemies aléatoires",
                type: "ALL",
                targetTeam: "OPPONENT",
                comparisonId: null,
                tagId: null,
                maxTargets: 3,
                targetSelectionMode: "RANDOM",
            },
            {
                internalLabel: "Galadrim - Serviteur allié (ciblé)",
                type: "MINION",
                targetTeam: "PLAYER",
                comparisonId: null,
                tagId: null,
            },
            {
                internalLabel: "Galadrim - Serviteur (ciblé)",
                type: "MINION",
                targetTeam: "ALL",
                comparisonId: null,
                tagId: null,
            },
            {
                internalLabel: "Galadrim - Autres développeurs alliés",
                type: "MINION",
                targetTeam: "PLAYER",
                comparisonId: null,
                tagId: developpeurTag.id,
                excludeSelf: true,
            },
            {
                internalLabel: "Galadrim - Autres pets alliés",
                type: "MINION",
                targetTeam: "PLAYER",
                comparisonId: null,
                tagId: petsTag.id,
                excludeSelf: true,
            },
            {
                internalLabel: "Galadrim - Autres serviteurs alliés",
                type: "MINION",
                targetTeam: "PLAYER",
                comparisonId: null,
                tagId: null,
                excludeSelf: true,
            },
        ]);

        const [
            boostPlusOneAttack,
            boostPlusOneBoth,
            boostPlusTwoBothTaunt,
            boostPlusThreeBothTaunt,
            boostPlusThreeAttackCharge,
            boostChargeOnly,
            boostPlusOneBothAura,
            boostPlusOneSpellPower,
        ] = await Boost.createMany([
            {
                internalLabel: "Galadrim - +1 attaque",
                attack: 1,
                health: null,
                spellPower: null,
                minionPowerId: null,
            },
            {
                internalLabel: "Galadrim - +1/+1",
                attack: 1,
                health: 1,
                spellPower: null,
                minionPowerId: null,
            },
            {
                internalLabel: "Galadrim - +2/+2 Provocation",
                attack: 2,
                health: 2,
                spellPower: null,
                minionPowerId: tauntPower.id,
            },
            {
                internalLabel: "Galadrim - +3/+3 Provocation",
                attack: 3,
                health: 3,
                spellPower: null,
                minionPowerId: tauntPower.id,
            },
            {
                internalLabel: "Galadrim - +3 attaque Charge",
                attack: 3,
                health: null,
                spellPower: null,
                minionPowerId: chargePower.id,
            },
            {
                internalLabel: "Galadrim - Charge",
                attack: null,
                health: null,
                spellPower: null,
                minionPowerId: chargePower.id,
            },
            {
                internalLabel: "Galadrim - Aura +1/+1",
                attack: 1,
                health: 1,
                spellPower: null,
                minionPowerId: null,
            },
            {
                internalLabel: "Galadrim - +1 dégât de sort",
                attack: null,
                health: null,
                spellPower: 1,
                minionPowerId: null,
            },
        ]);

        const [
            drawSpellAction,
            drawDeveloppeurAction,
            drawCheapMinionAction,
            drawOneAction,
            drawTwoAction,
            drawTwoMinionsAction,
            enemyDrawOneAction,
            healHeroFourAction,
            healHeroFiveAction,
            healAllyMinionsThreeAction,
            healOtherMinionsTwoAction,
            damageOneHeroAction,
            devAigriDamageAction,
            massEnemyMinionDamageAction,
            damageFourHeroAction,
            damageFiveHeroAction,
            burnoutDamageAction,
            damageFourRandomAction,
            damageThreeAllMinionsAction,
            pmJuniorBoostAction,
            pmStresseChargeAction,
            directeurBoostAction,
            insomniaqueDamageAction,
            boostAllAlliesAction,
            sprintReviewBoostAction,
            heuresSupBoostAction,
            goodiesHealAction,
        ] = await Action.createMany([
            {
                internalLabel: "Stagiaire Dev - Pioche un sort",
                type: "DRAW",
                isTargeted: false,
                ...nullActionFields,
                drawCount: 1,
                drawCardFilterId: spellDrawFilter.id,
            },
            {
                internalLabel: "Dev Back-End - Pioche un développeur",
                type: "DRAW",
                isTargeted: false,
                ...nullActionFields,
                drawCount: 1,
                drawCardFilterId: developpeurDrawFilter.id,
            },
            {
                internalLabel: "Recruteur RH - Pioche serviteur coût ≤ 3",
                type: "DRAW",
                isTargeted: false,
                ...nullActionFields,
                drawCount: 1,
                drawCardFilterId: cheapMinionDrawFilter.id,
            },
            {
                internalLabel: "Galadrim - Pioche 1",
                type: "DRAW",
                isTargeted: false,
                ...nullActionFields,
                drawCount: 1,
            },
            {
                internalLabel: "Galadrim - Pioche 2",
                type: "DRAW",
                isTargeted: false,
                ...nullActionFields,
                drawCount: 2,
            },
            {
                internalLabel: "Team Building - Pioche 2 serviteurs",
                type: "DRAW",
                isTargeted: false,
                ...nullActionFields,
                drawCount: 2,
                drawCardFilterId: minionDrawFilter.id,
            },
            {
                internalLabel: "Sales Charismatique - Adversaire pioche 1",
                type: "ENEMY_DRAW",
                isTargeted: false,
                ...nullActionFields,
                enemyDrawCount: 1,
            },
            {
                internalLabel: "Happiness Manager - 4 soins héros",
                type: "HEAL",
                isTargeted: false,
                ...nullActionFields,
                heal: 4,
            },
            {
                internalLabel: "Dev Front-End - 5 soins héros",
                type: "HEAL",
                isTargeted: false,
                ...nullActionFields,
                heal: 5,
            },
            {
                internalLabel: "Manager Bienveillant - 3 soins serviteurs alliés",
                type: "HEAL",
                isTargeted: false,
                ...nullActionFields,
                heal: 3,
            },
            {
                internalLabel: "Agiliste Convaincu - 2 soins autres serviteurs",
                type: "HEAL",
                isTargeted: false,
                ...nullActionFields,
                heal: 2,
            },
            {
                internalLabel: "BizDev Débutant - 1 dégât héros adverse",
                type: "DAMAGE",
                isTargeted: false,
                ...nullActionFields,
                damage: 1,
            },
            {
                internalLabel: "Dev Aigri - 2 dégâts serviteur ciblé",
                type: "DAMAGE",
                isTargeted: true,
                ...nullActionFields,
                damage: 2,
            },
            {
                internalLabel:
                    "Architecte Système / Réunion Interminable - 3 dégâts serviteurs adverses",
                type: "DAMAGE",
                isTargeted: false,
                ...nullActionFields,
                damage: 3,
            },
            {
                internalLabel: "Négociateur - 4 dégâts héros adverse",
                type: "DAMAGE",
                isTargeted: false,
                ...nullActionFields,
                damage: 4,
            },
            {
                internalLabel: "Directeur Commercial - 5 dégâts héros adverse",
                type: "DAMAGE",
                isTargeted: false,
                ...nullActionFields,
                damage: 5,
            },
            {
                internalLabel: "Burnout - 6 dégâts serviteur ciblé",
                type: "DAMAGE",
                isTargeted: true,
                ...nullActionFields,
                damage: 6,
            },
            {
                internalLabel: "Coupure Internet - 4 dégâts aléatoires",
                type: "DAMAGE",
                isTargeted: false,
                ...nullActionFields,
                damage: 4,
            },
            {
                internalLabel: "Bug en Prod - 3 dégâts tous serviteurs",
                type: "DAMAGE",
                isTargeted: false,
                ...nullActionFields,
                damage: 3,
            },
            {
                internalLabel: "PM Junior - +1 attaque ciblé",
                type: "BOOST",
                isTargeted: true,
                ...nullActionFields,
                boostId: boostPlusOneAttack.id,
            },
            {
                internalLabel: "PM Stressé - Charge ciblé",
                type: "BOOST",
                isTargeted: true,
                ...nullActionFields,
                boostId: boostChargeOnly.id,
            },
            {
                internalLabel: "Directeur de Projet - +2/+2 Provocation ciblé",
                type: "BOOST",
                isTargeted: true,
                ...nullActionFields,
                boostId: boostPlusTwoBothTaunt.id,
            },
            {
                internalLabel: "Dev Insomniaque - 2 dégâts héros adverse",
                type: "DAMAGE",
                isTargeted: false,
                ...nullActionFields,
                damage: 2,
            },
            {
                internalLabel: "Pause Café - +1/+1 serviteurs alliés",
                type: "BOOST",
                isTargeted: false,
                ...nullActionFields,
                boostId: boostPlusOneBoth.id,
            },
            {
                internalLabel: "Sprint Review - +3/+3 Provocation ciblé",
                type: "BOOST",
                isTargeted: true,
                ...nullActionFields,
                boostId: boostPlusThreeBothTaunt.id,
            },
            {
                internalLabel: "Heures Sup' - +3 attaque Charge ciblé",
                type: "BOOST",
                isTargeted: true,
                ...nullActionFields,
                boostId: boostPlusThreeAttackCharge.id,
            },
            {
                internalLabel: "Goodies Galadrim - 5 soins serviteur ciblé",
                type: "HEAL",
                isTargeted: true,
                ...nullActionFields,
                heal: 5,
            },
        ]);

        await ToolToTarget.createMany([
            { targetId: allyHeroTarget.id, actionId: healHeroFourAction.id, boostId: null },
            { targetId: allyHeroTarget.id, actionId: healHeroFiveAction.id, boostId: null },
            {
                targetId: allyMinionsTarget.id,
                actionId: healAllyMinionsThreeAction.id,
                boostId: null,
            },
            {
                targetId: otherAllyMinionsTarget.id,
                actionId: healOtherMinionsTwoAction.id,
                boostId: null,
            },
            { targetId: enemyHeroTarget.id, actionId: damageOneHeroAction.id, boostId: null },
            {
                targetId: targetedAnyMinionTarget.id,
                actionId: devAigriDamageAction.id,
                boostId: null,
            },
            {
                targetId: enemyMinionsTarget.id,
                actionId: massEnemyMinionDamageAction.id,
                boostId: null,
            },
            { targetId: enemyHeroTarget.id, actionId: damageFourHeroAction.id, boostId: null },
            { targetId: enemyHeroTarget.id, actionId: damageFiveHeroAction.id, boostId: null },
            {
                targetId: targetedAnyMinionTarget.id,
                actionId: burnoutDamageAction.id,
                boostId: null,
            },
            { targetId: randomEnemyTarget.id, actionId: damageFourRandomAction.id, boostId: null },
            {
                targetId: allMinionsTarget.id,
                actionId: damageThreeAllMinionsAction.id,
                boostId: null,
            },
            {
                targetId: targetedAllyMinionTarget.id,
                actionId: pmJuniorBoostAction.id,
                boostId: null,
            },
            {
                targetId: targetedAllyMinionTarget.id,
                actionId: pmStresseChargeAction.id,
                boostId: null,
            },
            {
                targetId: targetedAllyMinionTarget.id,
                actionId: directeurBoostAction.id,
                boostId: null,
            },
            { targetId: enemyHeroTarget.id, actionId: insomniaqueDamageAction.id, boostId: null },
            { targetId: allyMinionsTarget.id, actionId: boostAllAlliesAction.id, boostId: null },
            {
                targetId: targetedAllyMinionTarget.id,
                actionId: sprintReviewBoostAction.id,
                boostId: null,
            },
            {
                targetId: targetedAllyMinionTarget.id,
                actionId: heuresSupBoostAction.id,
                boostId: null,
            },
            {
                targetId: targetedAllyMinionTarget.id,
                actionId: goodiesHealAction.id,
                boostId: null,
            },
            {
                targetId: otherDeveloppeursTarget.id,
                actionId: null,
                boostId: boostPlusOneBothAura.id,
            },
            { targetId: otherPetsTarget.id, actionId: null, boostId: boostPlusOneBothAura.id },
            { targetId: allyHeroTarget.id, actionId: null, boostId: boostPlusOneSpellPower.id },
        ]);

        const [
            scrumMasterPassive,
            devAguerriPassive,
            mascottePassive,
            insomniaquePassive,
            productOwnerPassive,
            agilistePassive,
            bizDevPassive,
            nantaisCreatifPassive,
        ] = await Passive.createMany([
            {
                internalLabel: "Scrum Master - aura développeurs",
                type: "BOOST",
                triggersOn: null,
                actionId: null,
                boostId: boostPlusOneBothAura.id,
            },
            {
                internalLabel: "Dev Aguerri - aura spell power",
                type: "BOOST",
                triggersOn: null,
                actionId: null,
                boostId: boostPlusOneSpellPower.id,
            },
            {
                internalLabel: "Mascotte du Bureau - aura pets",
                type: "BOOST",
                triggersOn: null,
                actionId: null,
                boostId: boostPlusOneBothAura.id,
            },
            {
                internalLabel: "Dev Insomniaque - pioche réactive",
                type: "ACTION",
                triggersOn: "DRAW",
                actionId: insomniaqueDamageAction.id,
                boostId: null,
            },
            {
                internalLabel: "Product Owner - début de tour pioche",
                type: "ACTION",
                triggersOn: "TURN_BEGIN",
                actionId: drawOneAction.id,
                boostId: null,
            },
            {
                internalLabel: "Agiliste Convaincu - fin de tour soins",
                type: "ACTION",
                triggersOn: "TURN_END",
                actionId: healOtherMinionsTwoAction.id,
                boostId: null,
            },
            {
                internalLabel: "BizDev Débutant - fin de tour dégâts",
                type: "ACTION",
                triggersOn: "TURN_END",
                actionId: damageOneHeroAction.id,
                boostId: null,
            },
            {
                internalLabel: "Nantais Créatif - fin de tour pioche",
                type: "ACTION",
                triggersOn: "TURN_END",
                actionId: drawOneAction.id,
                boostId: null,
            },
        ]);

        const [
            stagiaireDev,
            devFrontEnd,
            devBackEnd,
            devAigri,
            qaTesteur,
            devAguerri,
            devInsomniaque,
            architecteSysteme,
            pmJunior,
            scrumMaster,
            pmStresse,
            productOwner,
            directeurProjet,
            agilisteConvaincu,
            bizDevDebutant,
            salesCharismatique,
            closerAffame,
            negociateur,
            keyAccountManager,
            directeurCommercial,
            agentSupport,
            happinessManager,
            recruteurRh,
            managerBienveillant,
            supportDeNuit,
            parisienPresse,
            parisienBobo,
            nantaisDetendu,
            nantaisCreatif,
            lyonnaisGourmand,
            mascotteDuBureau,
            chatSurLeClavier,
            chienFoufou,
            planteVerte,
        ] = await Minion.createMany([
            { internalLabel: "Stagiaire Dev", attack: 1, health: 1 },
            { internalLabel: "Dev Front-End", attack: 2, health: 3 },
            { internalLabel: "Dev Back-End", attack: 2, health: 3 },
            { internalLabel: "Dev Aigri", attack: 2, health: 3, minionPowerId: tauntPower.id },
            {
                internalLabel: "QA Testeur Impitoyable",
                attack: 1,
                health: 4,
                minionPowerId: poisonousPower.id,
            },
            { internalLabel: "Dev Aguerri", attack: 4, health: 5 },
            { internalLabel: "Dev Insomniaque", attack: 4, health: 5 },
            { internalLabel: "Architecte Système", attack: 6, health: 6 },
            { internalLabel: "PM Junior", attack: 1, health: 2 },
            { internalLabel: "Scrum Master", attack: 2, health: 4 },
            { internalLabel: "PM Stressé", attack: 3, health: 2 },
            { internalLabel: "Product Owner", attack: 3, health: 4 },
            { internalLabel: "Directeur de Projet", attack: 4, health: 4 },
            { internalLabel: "Agiliste Convaincu", attack: 1, health: 4 },
            { internalLabel: "BizDev Débutant", attack: 1, health: 3 },
            { internalLabel: "Sales Charismatique", attack: 2, health: 3 },
            {
                internalLabel: "Closer Affamé",
                attack: 3,
                health: 2,
                minionPowerId: windfuryPower.id,
            },
            { internalLabel: "Négociateur", attack: 4, health: 4 },
            {
                internalLabel: "Key Account Manager",
                attack: 6,
                health: 5,
                minionPowerId: chargePower.id,
            },
            { internalLabel: "Directeur Commercial", attack: 5, health: 5 },
            { internalLabel: "Agent Support", attack: 1, health: 3, minionPowerId: tauntPower.id },
            { internalLabel: "Happiness Manager", attack: 2, health: 3 },
            { internalLabel: "Recruteur RH", attack: 2, health: 4 },
            {
                internalLabel: "Manager Bienveillant",
                attack: 3,
                health: 5,
                minionPowerId: tauntPower.id,
            },
            {
                internalLabel: "Support de Nuit",
                attack: 4,
                health: 7,
                minionPowerId: tauntPower.id,
            },
            {
                internalLabel: "Parisien Pressé",
                attack: 3,
                health: 1,
                minionPowerId: chargePower.id,
            },
            { internalLabel: "Parisien Bobo", attack: 2, health: 3 },
            { internalLabel: "Nantais Détendu", attack: 3, health: 4 },
            { internalLabel: "Nantais Créatif", attack: 3, health: 3 },
            { internalLabel: "Lyonnais Gourmand", attack: 4, health: 5 },
            { internalLabel: "Mascotte du Bureau", attack: 1, health: 1 },
            {
                internalLabel: "Chat sur le Clavier",
                attack: 1,
                health: 2,
                minionPowerId: tauntPower.id,
            },
            { internalLabel: "Chien Foufou", attack: 3, health: 2, minionPowerId: chargePower.id },
            { internalLabel: "Plante Verte", attack: 0, health: 4, minionPowerId: tauntPower.id },
        ]);

        await MinionBattlecryAction.createMany([
            { minionId: stagiaireDev.id, actionId: drawSpellAction.id },
            { minionId: devFrontEnd.id, actionId: healHeroFiveAction.id },
            { minionId: devAigri.id, actionId: devAigriDamageAction.id },
            { minionId: architecteSysteme.id, actionId: massEnemyMinionDamageAction.id },
            { minionId: pmJunior.id, actionId: pmJuniorBoostAction.id },
            { minionId: pmStresse.id, actionId: pmStresseChargeAction.id },
            { minionId: directeurProjet.id, actionId: directeurBoostAction.id },
            { minionId: salesCharismatique.id, actionId: drawOneAction.id },
            { minionId: salesCharismatique.id, actionId: enemyDrawOneAction.id },
            { minionId: negociateur.id, actionId: damageFourHeroAction.id },
            { minionId: happinessManager.id, actionId: healHeroFourAction.id },
            { minionId: recruteurRh.id, actionId: drawCheapMinionAction.id },
            { minionId: parisienBobo.id, actionId: drawSpellAction.id },
        ]);

        await MinionDeathrattleAction.createMany([
            { minionId: devBackEnd.id, actionId: drawDeveloppeurAction.id },
            { minionId: directeurCommercial.id, actionId: damageFiveHeroAction.id },
            { minionId: managerBienveillant.id, actionId: healAllyMinionsThreeAction.id },
            { minionId: lyonnaisGourmand.id, actionId: healHeroFourAction.id },
            { minionId: chatSurLeClavier.id, actionId: drawOneAction.id },
        ]);

        await MinionPassive.createMany([
            { minionId: devAguerri.id, passiveId: devAguerriPassive.id },
            { minionId: devInsomniaque.id, passiveId: insomniaquePassive.id },
            { minionId: scrumMaster.id, passiveId: scrumMasterPassive.id },
            { minionId: productOwner.id, passiveId: productOwnerPassive.id },
            { minionId: agilisteConvaincu.id, passiveId: agilistePassive.id },
            { minionId: bizDevDebutant.id, passiveId: bizDevPassive.id },
            { minionId: nantaisCreatif.id, passiveId: nantaisCreatifPassive.id },
            { minionId: mascotteDuBureau.id, passiveId: mascottePassive.id },
        ]);

        const minionCards = await Card.createMany([
            {
                label: "Stagiaire Dev",
                imageUrl: getGaladrimCardImage("Stagiaire Dev"),
                cost: 1,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: stagiaireDev.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Dev Front-End",
                imageUrl: getGaladrimCardImage("Dev Front-End"),
                cost: 2,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: devFrontEnd.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Dev Back-End",
                imageUrl: getGaladrimCardImage("Dev Back-End"),
                cost: 2,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: devBackEnd.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Dev Aigri",
                imageUrl: getGaladrimCardImage("Dev Aigri"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: devAigri.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "QA Testeur Impitoyable",
                imageUrl: getGaladrimCardImage("QA Testeur Impitoyable"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: qaTesteur.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Dev Aguerri",
                imageUrl: getGaladrimCardImage("Dev Aguerri"),
                cost: 4,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: devAguerri.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Dev Insomniaque",
                imageUrl: getGaladrimCardImage("Dev Insomniaque"),
                cost: 5,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: devInsomniaque.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Architecte Système",
                imageUrl: getGaladrimCardImage("Architecte Système"),
                cost: 7,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: architecteSysteme.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "PM Junior",
                imageUrl: getGaladrimCardImage("PM Junior"),
                cost: 1,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: pmJunior.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Scrum Master",
                imageUrl: getGaladrimCardImage("Scrum Master"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: scrumMaster.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "PM Stressé",
                imageUrl: getGaladrimCardImage("PM Stressé"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: pmStresse.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Product Owner",
                imageUrl: getGaladrimCardImage("Product Owner"),
                cost: 4,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: productOwner.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Directeur de Projet",
                imageUrl: getGaladrimCardImage("Directeur de Projet"),
                cost: 5,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: directeurProjet.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Agiliste Convaincu",
                imageUrl: getGaladrimCardImage("Agiliste Convaincu"),
                cost: 2,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: agilisteConvaincu.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "BizDev Débutant",
                imageUrl: getGaladrimCardImage("BizDev Débutant"),
                cost: 1,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: bizDevDebutant.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Sales Charismatique",
                imageUrl: getGaladrimCardImage("Sales Charismatique"),
                cost: 2,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: salesCharismatique.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Closer Affamé",
                imageUrl: getGaladrimCardImage("Closer Affamé"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: closerAffame.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Négociateur",
                imageUrl: getGaladrimCardImage("Négociateur"),
                cost: 4,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: negociateur.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Key Account Manager",
                imageUrl: getGaladrimCardImage("Key Account Manager"),
                cost: 6,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: keyAccountManager.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Directeur Commercial",
                imageUrl: getGaladrimCardImage("Directeur Commercial"),
                cost: 6,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: directeurCommercial.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Agent Support",
                imageUrl: getGaladrimCardImage("Agent Support"),
                cost: 1,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: agentSupport.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Happiness Manager",
                imageUrl: getGaladrimCardImage("Happiness Manager"),
                cost: 2,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: happinessManager.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Recruteur RH",
                imageUrl: getGaladrimCardImage("Recruteur RH"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: recruteurRh.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Manager Bienveillant",
                imageUrl: getGaladrimCardImage("Manager Bienveillant"),
                cost: 4,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: managerBienveillant.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Support de Nuit",
                imageUrl: getGaladrimCardImage("Support de Nuit"),
                cost: 5,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: supportDeNuit.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Parisien Pressé",
                imageUrl: getGaladrimCardImage("Parisien Pressé"),
                cost: 2,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: parisienPresse.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Parisien Bobo",
                imageUrl: getGaladrimCardImage("Parisien Bobo"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: parisienBobo.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Nantais Détendu",
                imageUrl: getGaladrimCardImage("Nantais Détendu"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: nantaisDetendu.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Nantais Créatif",
                imageUrl: getGaladrimCardImage("Nantais Créatif"),
                cost: 4,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: nantaisCreatif.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Lyonnais Gourmand",
                imageUrl: getGaladrimCardImage("Lyonnais Gourmand"),
                cost: 4,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: lyonnaisGourmand.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Mascotte du Bureau",
                imageUrl: getGaladrimCardImage("Mascotte du Bureau"),
                cost: 1,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: mascotteDuBureau.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Chat sur le Clavier",
                imageUrl: getGaladrimCardImage("Chat sur le Clavier"),
                cost: 2,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: chatSurLeClavier.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Chien Foufou",
                imageUrl: getGaladrimCardImage("Chien Foufou"),
                cost: 3,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: chienFoufou.id,
                spellId: null,
                weaponId: null,
            },
            {
                label: "Plante Verte",
                imageUrl: getGaladrimCardImage("Plante Verte"),
                cost: 1,
                type: "MINION",
                cardSetId: galadrimSet.id,
                minionId: planteVerte.id,
                spellId: null,
                weaponId: null,
            },
        ]);

        const developpeurCardIndices = [0, 1, 2, 3, 4, 5, 6, 7];
        const pmCardIndices = [8, 9, 10, 11, 12, 13];
        const geoPetTagIndices: Array<[number, typeof parisienTag]> = [
            [25, parisienTag],
            [26, parisienTag],
            [27, nantaisTag],
            [28, nantaisTag],
            [29, lyonnaisTag],
            [30, petsTag],
            [31, petsTag],
            [32, petsTag],
        ];

        await CardTag.createMany([
            ...developpeurCardIndices.map((index) => ({
                cardId: minionCards[index]!.id,
                tagId: developpeurTag.id,
            })),
            ...pmCardIndices.map((index) => ({
                cardId: minionCards[index]!.id,
                tagId: pmTag.id,
            })),
            ...geoPetTagIndices.map(([index, tag]) => ({
                cardId: minionCards[index]!.id,
                tagId: tag.id,
            })),
        ]);

        const cableDeathrattleDamageAction = await Action.create({
            internalLabel: "Câble Réseau - 2 dégâts serviteurs adverses",
            type: "DAMAGE",
            isTargeted: false,
            ...nullActionFields,
            damage: 2,
        });

        await ToolToTarget.create({
            targetId: enemyMinionsTarget.id,
            actionId: cableDeathrattleDamageAction.id,
            boostId: null,
        });

        const weaponDrawAction = await Action.create({
            internalLabel: "Clavier Mécanique - Pioche 1",
            type: "DRAW",
            isTargeted: false,
            ...nullActionFields,
            drawCount: 1,
        });

        const [
            pauseCafeSpell,
            bugEnProdSpell,
            deploiementReussiSpell,
            reunionInterminableSpell,
            sprintReviewSpell,
            heuresSupSpell,
            burnoutSpell,
            teamBuildingSpell,
            goodiesGaladrimSpell,
            coupureInternetSpell,
        ] = await Spell.createMany([
            { internalLabel: "Pause Café", actionId: boostAllAlliesAction.id },
            { internalLabel: "Bug en Prod", actionId: damageThreeAllMinionsAction.id },
            { internalLabel: "Déploiement Réussi", actionId: drawTwoAction.id },
            { internalLabel: "Réunion Interminable", actionId: massEnemyMinionDamageAction.id },
            { internalLabel: "Sprint Review", actionId: sprintReviewBoostAction.id },
            { internalLabel: "Heures Sup'", actionId: heuresSupBoostAction.id },
            { internalLabel: "Burnout", actionId: burnoutDamageAction.id },
            { internalLabel: "Team Building", actionId: drawTwoMinionsAction.id },
            { internalLabel: "Goodies Galadrim", actionId: goodiesHealAction.id },
            { internalLabel: "Coupure Internet", actionId: damageFourRandomAction.id },
        ]);

        const [tasseCafe, clavierMecanique, cableReseau] = await Weapon.createMany([
            { internalLabel: "Tasse à Café Ébréchée", damage: 1, durability: 4 },
            { internalLabel: "Clavier Mécanique", damage: 2, durability: 2 },
            { internalLabel: "Câble Réseau", damage: 4, durability: 2 },
        ]);

        await WeaponDeathrattleAction.createMany([
            { weaponId: clavierMecanique.id, actionId: weaponDrawAction.id },
            { weaponId: cableReseau.id, actionId: cableDeathrattleDamageAction.id },
        ]);

        await Card.createMany([
            {
                label: "Pause Café",
                imageUrl: getGaladrimCardImage("Pause Café"),
                cost: 2,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: pauseCafeSpell.id,
                weaponId: null,
            },
            {
                label: "Bug en Prod",
                imageUrl: getGaladrimCardImage("Bug en Prod"),
                cost: 4,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: bugEnProdSpell.id,
                weaponId: null,
            },
            {
                label: "Déploiement Réussi",
                imageUrl: getGaladrimCardImage("Déploiement Réussi"),
                cost: 3,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: deploiementReussiSpell.id,
                weaponId: null,
            },
            {
                label: "Réunion Interminable",
                imageUrl: getGaladrimCardImage("Réunion Interminable"),
                cost: 3,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: reunionInterminableSpell.id,
                weaponId: null,
            },
            {
                label: "Sprint Review",
                imageUrl: getGaladrimCardImage("Sprint Review"),
                cost: 4,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: sprintReviewSpell.id,
                weaponId: null,
            },
            {
                label: "Heures Sup'",
                imageUrl: getGaladrimCardImage("Heures Sup'"),
                cost: 3,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: heuresSupSpell.id,
                weaponId: null,
            },
            {
                label: "Burnout",
                imageUrl: getGaladrimCardImage("Burnout"),
                cost: 4,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: burnoutSpell.id,
                weaponId: null,
            },
            {
                label: "Team Building",
                imageUrl: getGaladrimCardImage("Team Building"),
                cost: 3,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: teamBuildingSpell.id,
                weaponId: null,
            },
            {
                label: "Goodies Galadrim",
                imageUrl: getGaladrimCardImage("Goodies Galadrim"),
                cost: 1,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: goodiesGaladrimSpell.id,
                weaponId: null,
            },
            {
                label: "Coupure Internet",
                imageUrl: getGaladrimCardImage("Coupure Internet"),
                cost: 6,
                type: "SPELL",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: coupureInternetSpell.id,
                weaponId: null,
            },
            {
                label: "Tasse à Café Ébréchée",
                imageUrl: getGaladrimCardImage("Tasse à Café Ébréchée"),
                cost: 1,
                type: "WEAPON",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: null,
                weaponId: tasseCafe.id,
            },
            {
                label: "Clavier Mécanique",
                imageUrl: getGaladrimCardImage("Clavier Mécanique"),
                cost: 2,
                type: "WEAPON",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: null,
                weaponId: clavierMecanique.id,
            },
            {
                label: "Câble Réseau",
                imageUrl: getGaladrimCardImage("Câble Réseau"),
                cost: 4,
                type: "WEAPON",
                cardSetId: galadrimSet.id,
                minionId: null,
                spellId: null,
                weaponId: cableReseau.id,
            },
        ]);
    }
}
