/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
    auth: {
        AdominLogin: () => import("#controllers/auth/adomin_login"),
        AdominLogout: () => import("#controllers/auth/adomin_logout"),
        Auth: () => import("#controllers/auth/auth_controller"),
        Me: () => import("#controllers/auth/me"),
        Register: () => import("#controllers/auth/register"),
        socket: {
            AuthRestrictedEvents: () => import("#controllers/auth/socket/auth_restricted_events"),
            Index: () => import("#controllers/auth/socket/index"),
            SocketAuth: () => import("#controllers/auth/socket/socket_auth"),
            SocketLogout: () => import("#controllers/auth/socket/socket_logout"),
        },
        UpdateAvatar: () => import("#controllers/auth/update_avatar"),
    },
    cardSets: {
        CardSets: () => import("#controllers/card_sets/card_sets_controller"),
        ListCardSets: () => import("#controllers/card_sets/list_card_sets"),
    },
    cards: {
        Cards: () => import("#controllers/cards/cards_controller"),
        ListCards: () => import("#controllers/cards/list_cards"),
    },
    collection: {
        Collection: () => import("#controllers/collection/collection_controller"),
        CollectionValidators: () => import("#controllers/collection/collection_validators"),
    },
    dailyQuests: {
        DailyQuests: () => import("#controllers/daily_quests/daily_quests_controller"),
    },
    deckShares: {
        DeckShareValidators: () => import("#controllers/deck_shares/deck_share_validators"),
        DeckShares: () => import("#controllers/deck_shares/deck_shares_controller"),
        SerializeDeckShare: () => import("#controllers/deck_shares/serialize_deck_share"),
    },
    decks: {
        DeckUtils: () => import("#controllers/decks/deck_utils"),
        DeckValidators: () => import("#controllers/decks/deck_validators"),
        Decks: () => import("#controllers/decks/decks_controller"),
        SerializeDeck: () => import("#controllers/decks/serialize_deck"),
    },
    events: {
        Events: () => import("#controllers/events/events_controller"),
    },
    friends: {
        FriendRequests: () => import("#controllers/friends/friend_requests_controller"),
        Friends: () => import("#controllers/friends/friends_controller"),
        FriendsValidators: () => import("#controllers/friends/friends_validators"),
    },
    gameHistory: {
        GameHistory: () => import("#controllers/game_history/game_history_controller"),
        ListUserGames: () => import("#controllers/game_history/list_user_games"),
        SerializeGameHistory: () => import("#controllers/game_history/serialize_game_history"),
        ShowGameReplay: () => import("#controllers/game_history/show_game_replay"),
        ShowUserGame: () => import("#controllers/game_history/show_user_game"),
    },
    gameInvites: {
        GameInviteValidators: () => import("#controllers/game_invites/game_invite_validators"),
        GameInvites: () => import("#controllers/game_invites/game_invites_controller"),
    },
    games: {
        AbandonGame: () => import("#controllers/games/abandon_game"),
        CancelGameSearch: () => import("#controllers/games/cancel_game_search"),
        CountActiveGames: () => import("#controllers/games/count_active_games"),
        CreateGame: () => import("#controllers/games/create_game"),
        CreateTrainingGame: () => import("#controllers/games/create_training_game"),
        discover: {
            EnsureNoPendingDiscover: () =>
                import("#controllers/games/discover/ensure_no_pending_discover"),
            GameDiscoverChoice: () => import("#controllers/games/discover/game_discover_choice"),
        },
        GameSearchHeartbeat: () => import("#controllers/games/game_search_heartbeat"),
        GameSearch: () => import("#controllers/games/game_search"),
        GameUtils: () => import("#controllers/games/game_utils"),
        Games: () => import("#controllers/games/games_controller"),
        GeneratePlayerCards: () => import("#controllers/games/generate_player_cards"),
        minionAction: {
            CompleteMinionAttack: () =>
                import("#controllers/games/minion_action/complete_minion_attack"),
            GameMinionAction: () => import("#controllers/games/minion_action/game_minion_action"),
            MinionToHeroAction: () =>
                import("#controllers/games/minion_action/minion_to_hero_action"),
            MinionToMinionAction: () =>
                import("#controllers/games/minion_action/minion_to_minion_action"),
        },
        mulligan: {
            FinalizeMulligan: () => import("#controllers/games/mulligan/finalize_mulligan"),
            GameMulligan: () => import("#controllers/games/mulligan/game_mulligan"),
            PerformMulligan: () => import("#controllers/games/mulligan/perform_mulligan"),
        },
        PassGameTurn: () => import("#controllers/games/pass_game_turn"),
        playCard: {
            BreakWeapon: () => import("#controllers/games/play_card/break_weapon"),
            GamePlayCard: () => import("#controllers/games/play_card/game_play_card"),
            InstantiateMinion: () => import("#controllers/games/play_card/instantiate_minion"),
            InstantiateWeapon: () => import("#controllers/games/play_card/instantiate_weapon"),
            PlayMinion: () => import("#controllers/games/play_card/play_minion"),
            PlaySpell: () => import("#controllers/games/play_card/play_spell"),
            PlayWeapon: () => import("#controllers/games/play_card/play_weapon"),
        },
        SendGameUpdate: () => import("#controllers/games/send_game_update"),
        SetupNextGameTurn: () => import("#controllers/games/setup_next_game_turn"),
        ShowGame: () => import("#controllers/games/show_game"),
        spectator: {
            GameWatch: () => import("#controllers/games/spectator/game_watch"),
        },
        TerminateGame: () => import("#controllers/games/terminate_game"),
        weaponAction: {
            GameWeaponAction: () => import("#controllers/games/weapon_action/game_weapon_action"),
            ReduceWeaponDurability: () =>
                import("#controllers/games/weapon_action/reduce_weapon_durability"),
            WeaponToHeroAction: () =>
                import("#controllers/games/weapon_action/weapon_to_hero_action"),
            WeaponToMinionAction: () =>
                import("#controllers/games/weapon_action/weapon_to_minion_action"),
        },
    },
    leaderboard: {
        Leaderboard: () => import("#controllers/leaderboard/leaderboard_controller"),
    },
    presence: {
        Presence: () => import("#controllers/presence/presence_controller"),
    },
    progression: {
        Progression: () => import("#controllers/progression/progression_controller"),
    },
    rewards: {
        Rewards: () => import("#controllers/rewards/rewards_controller"),
    },
};
