/**
 * Mapping label seedé → ID carte Hearthstone.
 * Généré / validé par scripts/generate_hs_card_ids.ts
 */
export const CARD_HS_IDS: Record<string, string> = {
    Abomination: "EX1_097",
    "Baron Geddon": "EX1_249",
    "Capitaine des mers du Sud": "NEW1_027",
    "Chasseur de bêtes": "EX1_531",
    "Chasseur de gros gibier": "EX1_005",
    "Chevalier de Hurlevent": "CS2_131",
    "Chef de guerre murloc": "EX1_507",
    "Cobra empereur": "EX1_170",
    "Commandant argenté": "EX1_067",
    "Commissaire-priseur de Gadgetzan": "EX1_095",
    "Corsaire redoutable": "NEW1_022",
    "Défenseur d'Argus": "EX1_093",
    Démolisseur: "EX1_102",
    Dimetrodon: "EX1_tk29",
    "Doubles warglaives": "TU4e_007",
    "Drake du Crépuscule": "EX1_043",
    "Dragon mécanique": "BOT_066t",
    "Espion luminescent": "EX1_508",
    "Exécuteur de Quel'Thalas": "EX1_020",
    "Farseer de Thrallmar": "EX1_021",
    "Farseer du Cercle terrestre": "CS2_117",
    "Gardien de la Lumière": "EX1_001",
    "Géant des mers": "EX1_586",
    "Glaneur de butin": "EX1_096",
    "Gnome lépreux": "EX1_029",
    "Guerrier tauren": "EX1_390",
    "Guérisseur de terrain": "CS2_117",
    "Harpie furie des vents": "EX1_033",
    "Héritage de l'Empereur": "EX1_160",
    "Hogger Frappe !": "NEW1_040",
    "Jeune faucon-dragon": "CS2_169",
    "Lance-tonneau": "TU4c_002",
    "Leeroy Jenkins": "EX1_116",
    Lutin: "CS2_231",
    "Maître brasseur": "TU4f_005",
    "Maître-naturaliste": "EX1_534",
    "Mage ancien": "EX1_584",
    "Mage de sang Thalnos": "EX1_012",
    Malygos: "EX1_563",
    "Moine du Shado-Pan": "TU4f_003",
    "Mousquetaire de Forgefer": "CS2_141",
    "Nain de Sombrefer": "EX1_046",
    "Oracle luminescent": "EX1_050",
    "Patriarche dos-argenté": "CS2_127",
    Piétinement: "TU4c_004",
    "Porte-bouclier": "EX1_405",
    "Prêtresse d'Elune": "EX1_583",
    "Ragnaros le Seigneur du Feu": "EX1_298",
    "Rampant des fondrières": "CS1_069",
    "Salve ardente": "EX1_277",
    Sanglier: "CS2_boar",
    "Seigneur de l'Arène": "CS2_162",
    "Sergent abusif": "CS2_188",
    "Spectre apaisant": "EX1_011",
    "Tigre de Strangleronce": "EX1_028",
    "Tireur d'élite": "CS2_141",
    "Tireur de précision": "EX1_609",
    "Tueur de kodo": "NEW1_041",
    "Voyant luminescent": "EX1_103",
    "Warglaive d'Azzinoth": "BT_430",
    "Éclaireur pandaren": "TU4f_002",
};
